menu:
  Home: /
  Archives: /archives
  Git: https://github.com/livebug/livebug.github.io/tree/public

widgets:
- search
- category
# - tag
- tagcloud

excerpt_link: Read More

# twitter:
#   username:
#   show_replies: false
#   tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: true

fancybox: true

google_analytics:
rss:

# comment_provider: facebook
# # Facebook comment
# facebook:
#   appid: 123456789012345
#   comment_count: 5
#   comment_width: 840
#   comment_colorscheme: light

favicon:
  small: /images/favicon.ico
  #medium: /images/favicon-32x32-next.png
  medium: /images/favicon.ico
  # apple_touch_icon: /images/apple-touch-icon-next.png
  # safari_pinned_tab: /images/logo.svg
  #android_manifest: /manifest.json
# ————————————————
# 版权声明：本文为CSDN博主「RuiW_97」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
# 原文链接：https://blog.csdn.net/qq_39181839/article/details/109477357